### ISSUE TITLE
2. Create a Post

### ISSUE THREAD

**Issue by alishalabi** [MakeSchool-Tutorials/Node-Reddit-Clone#23]
Disclaimer: not really a bug, more of a clarifying point.

You cannot simply put a "require" statement in the middle of your code, you need to stuff it inside of a constant or a variable. 

Syntax:
`const posts = require('./controllers/posts.js')(app);`
Not just `require('./controllers/posts.js')(app);`

**Comment by droxey** [comment]
It's key to note that one _can_ import code in this fashion --- please see [this incredibly detailed write-up](https://medium.freecodecamp.org/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8) regarding the intricacies of requiring modules in the ES2017 Module standard. 

Recipe for Success: 
1. **if you need to use the output** of a module you're requiring in your code, **assign it a variable, then use that variable later on to call the module's exported functions**.  A good example? Using an `npm` module from a third party! Here's a code sample that assumes you've globally installed the [popular `request` library](https://www.npmjs.com/package/request): `npm install -g request`.
    ```js
    var request = require('request');
    request('http://www.google.com', function (error, response, body) {
        console.log('error:', error); // Print the error if one occurred
        console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
        console.log('body:', body); // Print the HTML for the Google homepage.
    });
    ```
1. If **you don't care about the output**, as in the example of our routes, **you can omit the variable declaration** entirely, simply utilizing the `require` statement to include the module's exported route declarations. This tells a far more succinct story about your intentions as a developer, and doesn't cause linting errors due to the declaration of an unused variable. 

Closing this ticket as there's no action item required here. @alishalabi, please re-open if you experience an issue with this code at a specific step in the tutorial.
